# Generated by Django 3.1.1 on 2020-09-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.suppliers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materia Prima',
                'ordering': ['id'],
            },
        ),
    ]
